apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: homework
  labels:
    app.kubernetes.io/name: backend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
